import cv2
import numpy as np

def colorToType (color):
	color = tuple(color)
	ct = {
		(0, 0, 0): 0,		# 黑：None 0
		(255, 255, 255): 1,	# 白：Road 1
		(0, 0, 255): 2,		# 红：Terminal 2
		(0, 255, 0): 3,		# 绿：Wall 3
		(0, 255, 255): 4	# 黄：Start 4
	}
	if ct.get(color, 15) == 15:
		print(color)
	return ct.get(color, 15)

image = cv2.imread('map16.png')
(m, n, _) = image.shape
mif = open('map.mif', 'w')
mif.write('-- Generated by MakeMif.py\n\n')
mif.writelines(['WIDTH=4;\n', 'DEPTH=%d;\n' % (m * n), 'ADDRESS_RADIX=HEX;\n', 'DATA_RADIX=HEX;\n'])
mif.write('\n')
mif.write('CONTENT BEGIN\n')
k = 0
for j in range(n):
	for i in range(m):
		mif.write('\t%03X : %x;\n' % (k, colorToType( image[i, j] )))
		k += 1
mif.write('END;\n')