import cv2
import numpy as np

base64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

img = np.zeros((16, 128*16), np.ubyte)
for i in range(128):
	cv2.putText(img, chr(i), (16*i + 2, 11), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 255)
cv2.imwrite('font.png', img)

mif = open('font.mif', 'w')
mif.write('-- Generated by make_font.py\n\n')
mif.writelines(['WIDTH=1;\n', 'DEPTH=%d;\n' % (128*16*16), 'ADDRESS_RADIX=HEX;\n', 'DATA_RADIX=HEX;\n'])
mif.write('\n')
mif.write('CONTENT BEGIN\n')


k = 0
for i in range(128):
	img = np.zeros((16, 16), np.ubyte)
	cv2.putText(img, chr(i), (2, 11), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 255)
	for line in img:
		for p in line:
			o = 1 if p == 255 else 0
			mif.write('\t%03X : %x;\n' % (k, o))
			k += 1

mif.write('END;\n')
