import cv2
import numpy as np

def colorToType (color):
	color = tuple(color)
	ct = {
		(128, 128, 128): 9,	# 黑：Hole 9
		(255, 255, 255): 1,	# 白：Ice 1
		(0, 0, 255): 8,		# 红：EndPoint 8
		(0, 255, 0): 6,		# 绿：IronWall 6
		(0, 255, 255): 7	# 黄：StartPoint 7
	}
	if ct.get(color, 0) == 0:
		print('undefined color: ', color)
	return ct.get(color, 0)

width = 6
image = cv2.imread('map.png')
(m, n, _) = image.shape
mif = open('map.mif', 'w')
mif.write('-- Generated by MakeMif.py\n\n')
mif.writelines(['WIDTH=%d;\n' % width, 'DEPTH=%d;\n' % (64*64), 'ADDRESS_RADIX=HEX;\n', 'DATA_RADIX=HEX;\n'])
mif.write('\n')
mif.write('CONTENT BEGIN\n')
k = 0
for i in range(64):
	for j in range(64):
		t = colorToType( image[i, j] ) if i < m and j < n else 0
		mif.write('\t%03X : %x;\n' % (k, t))
		k += 1
mif.write('END;\n')