import cv2
import numpy as np

# img = np.zeros((16, 64*16), np.ubyte)
# chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
# for i in range(64):
# 	cv2.putText(img, chars[i], (16*i + 2, 11), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 255)
# cv2.imwrite('font.png', img)

mif = open('font.mif', 'w')
mif.write('-- Generated by make_font.py\n\n')
mif.writelines(['WIDTH=1;\n', 'DEPTH=%d;\n' % (64*16*16), 'ADDRESS_RADIX=HEX;\n', 'DATA_RADIX=HEX;\n'])
mif.write('\n')
mif.write('CONTENT BEGIN\n')

chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
k = 0
for i in range(64):
	img = np.zeros((16, 16), np.ubyte)
	cv2.putText(img, chars[i], (2, 11), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 255)
	for line in img:
		for p in line:
			o = 1 if p == 255 else 0
			mif.write('\t%03X : %x;\n' % (k, o))
			k += 1

mif.write('END;\n')
